apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: counters
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 3600000
    segment.bytes: 1073741824
    
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: metrics
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 3600000
    segment.bytes: 1073741824
    
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: anomalies
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 3600000
    segment.bytes: 1073741824
   